=== cute-yellow-elephant/EPAM-Lab/XSLTWebApp/target/classes/categories.xsd
<?xml version="1.0" encoding="UTF-8"?>
		
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:categories="http://www.epam.by"
        targetNamespace="http://www.epam.by"> 
		
	<element name="categories">
       <complexType>
           <sequence>
           		<element name="category" type="categories:category" minOccurs="0" maxOccurs="unbounded"/>
           </sequence>
       </complexType>
    </element>	
    
    <complexType name="category">
    	<sequence>
        	<element name="subcategories" type="categories:subcategories"/>
        </sequence>
        <attribute name="name" type="ID" use="required"/>      
    </complexType>
    
    <complexType name="subcategories">
    	<sequence>
         	<element name="subcategory" type="categories:subcategory" minOccurs="0" maxOccurs="unbounded"/>
         </sequence>     
    </complexType>
    
    <complexType name="subcategory">
    	<sequence>
        	<element name="products" type="categories:products" />
        </sequence>
        <attribute name="name" type="string" use="required"/>      
    </complexType>
    
    <complexType name="products">
    	<sequence>
        	<element name="product" type="categories:product" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>     
    </complexType>
    
    <complexType name="product">
    	<sequence>
    		<element name="name" type="string"/>
        	<element name="provider" type="string"/>
        	<element name="model" type="categories:productModel"/>
        	<element name="date-of-issue" type="categories:productDate"/>
        	<element name="color" type="string"/>
        	<choice>
        		<element name="price" type="decimal"/>
        		<element name="not-in-stock" type="categories:inStockState"/>
        	</choice>      	
        </sequence>     
    </complexType>
    
    <simpleType name="inStockState">
	  <restriction base="string">
	  	<length value="0"/>
	  </restriction>
	</simpleType>
    
    <simpleType name="productModel">
        <restriction base="string">
            <pattern value="[a-zA-Z]{2}[0-9]{3}"/>
        </restriction>
    </simpleType>
    
    <simpleType name="productDate">
        <restriction base="string">
            <pattern value="((0[1-9]|[1-2]\d|3[01])-(0[13578]|1[02])|([0-2]\d|30)-(0[469]|11)|(0[1-9]|1\d|2[0-8])-02)-\d{4}|(0[1-9]|[12]\d)-02-(([02468][048]|[13579][26])00|(\d{2}([02468][48]|[2468][048]|[13579][26])))"/>
            <length value="10"/>
        </restriction>
    </simpleType>
		
</schema>

=== cute-yellow-elephant/EPAM-Lab/XSLTWebApp/src/main/resources/categories.xml
<?xml version="1.0" encoding="UTF-8"?>

<categories xmlns:categories="http://www.epam.by"
        	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        	xsi:schemaLocation="http://www.epam.by categories.xsd">
    <category name="food">
   		<subcategories>
   			<subcategory name="fruit">
   				<products>
   					<product>
   						<name>apple</name>
   						<provider>Poland</provider>
   						<model>AP123</model>
   						<date-of-issue>31-08-2014</date-of-issue>
   						<color>red</color>
   						<price>12.05</price>
   					</product>
   					<product>
   						<name>pineapple</name>
   						<provider>Africa</provider>
   						<model>PI123</model>
   						<date-of-issue>03-09-2014</date-of-issue>
   						<color>yellow</color>
   						<not-in-stock/>
   					</product>
   					<product>
   						<name>pear</name>
   						<provider>Poland</provider>
   						<model>PE123</model>
   						<date-of-issue>02-04-2014</date-of-issue>
   						<color>Green</color>
   						<price>9.05</price>
   					</product>
   				</products>	
   			</subcategory>				
   			<subcategory name="vegetables">
   				<products>
   					<product>
   						<name>tomato</name>
   						<provider>Brasil</provider>
   						<model>TM123</model>
   						<date-of-issue>13-09-2014</date-of-issue>
   						<color>red</color>
   						<price>4.05</price>
   					</product>
   					<product>
   						<name>name</name>
   						<provider>Belarus</provider>
   						<model>CC123</model>
   						<date-of-issue>06-09-2014</date-of-issue>
   						<color>green</color>
   						<price>8.35</price>
   					</product>
   					<product>
   						<name>potato</name>
   						<provider>Poland</provider>
   						<model>PT123</model>
   						<date-of-issue>09-04-2014</date-of-issue>
   						<color>brown</color>
   						<price>10.05</price>
   					</product>
   				</products>	
   			</subcategory>	  			
   		</subcategories>  
    </category>
    <category name="computers">
   		<subcategories>
   			<subcategory name="notebooks">
   				<products>
   					<product>
   						<name>MacBook</name>
   						<provider>Apple</provider>
   						<model>AR131</model>
   						<date-of-issue>31-08-2014</date-of-issue>
   						<color>gray</color>
   						<price>1300.00</price>
   					</product>
   					<product>
   						<name>XO359H</name>
   						<provider>ASUS</provider>
   						<model>XC550</model>
   						<date-of-issue>03-09-2014</date-of-issue>
   						<color>white</color>
   						<not-in-stock/>
   					</product>
   				</products>	
   			</subcategory>
   		</subcategories>  
    </category>
</categories>
